window.FS.initDOM = function() {
    window.FS.dom = {
        views: {
            home: document.getElementById('view-home'),
            main: document.getElementById('view-main'),
            results: document.getElementById('view-results')
        },
        modals: {
            settings: document.getElementById('modal-settings-backdrop'),
            calendar: document.getElementById('modal-calendar-backdrop'),
            docStats: document.getElementById('modal-doc-stats-backdrop'),
            compile: document.getElementById('modal-compile-backdrop')
        },
        // Header and Sidebar
        appLogo: document.getElementById('app-logo'),
        btnToggleSetup: document.getElementById('btn-toggle-setup'), // used as expand button
        btnSetupCollapse: document.getElementById('btn-setup-collapse'),
        btnShowSetupTab: document.getElementById('btn-show-setup-tab'),
        setupSidebar: document.getElementById('setup-sidebar'),
        btnExportBook: document.getElementById('btn-export-book'),
        btnSettings: document.getElementById('btn-settings'),
        btnCalendarStats: document.getElementById('btn-calendar-stats'),
        btnCloseCalendar: document.getElementById('btn-close-calendar'),
        btnPrevMonth: document.getElementById('btn-prev-month'),
        btnNextMonth: document.getElementById('btn-next-month'),
        calendarMonthYear: document.getElementById('calendar-month-year'),
        calendarDaysGrid: document.getElementById('calendar-days-grid'),
        calStatTotal: document.getElementById('cal-stat-total'),
        calStatAvg: document.getElementById('cal-stat-avg'),
        calStatStreak: document.getElementById('cal-stat-streak'),
        btnSidebarCollapse: document.getElementById('btn-sidebar-collapse'),
        btnSidebarExpand: document.getElementById('btn-sidebar-expand'),
        sidebarElement: document.getElementById('app-sidebar'),
        sidebarSearchInput: document.getElementById('sidebar-search-input'),
        sidebarTree: document.getElementById('sidebar-tree'),
        sidebarFilesCount: document.getElementById('sidebar-files-count'),
        headerDocPath: document.getElementById('header-doc-path'),
        headerDocTitle: document.getElementById('header-doc-title'),
        btnNewFile: document.getElementById('btn-new-file'),
        btnNewFolder: document.getElementById('btn-new-folder'),
        
        
        // Home View controls
        btnCreateWorkspace: document.getElementById('btn-create-workspace'),

        // Dashboard controls
        goalTypeToggle: document.getElementById('goal-type-toggle'),
        optionTime: document.getElementById('option-time'),
        optionWords: document.getElementById('option-words'),
        timePresets: document.getElementById('time-presets'),
        wordsPresets: document.getElementById('words-presets'),
        customTimeContainer: document.getElementById('custom-time-container'),
        customWordsContainer: document.getElementById('custom-words-container'),
        inputCustomTime: document.getElementById('input-custom-time'),
        inputCustomWords: document.getElementById('input-custom-words'),
        modeCards: document.querySelectorAll('.mode-card'),
        chkTypewriter: document.getElementById('chk-typewriter'),
        typewriterNoiseSettings: document.getElementById('typewriter-noise-settings'),
        chkAmbient: document.getElementById('chk-ambient'),
        selectAmbientType: document.getElementById('select-ambient-type'),
        ambientNoiseSettings: document.getElementById('ambient-noise-settings'),
        btnStartSession: document.getElementById('btn-start-session'),

        // Editor
        editorTextarea: document.getElementById('editor-textarea'),
        richTextToolbar: document.getElementById('rich-text-toolbar'),
        toolbarBtns: document.querySelectorAll('.toolbar-btn'),
        fontFamilySelect: document.getElementById('font-family-select'),
        fontSizeSelect: document.getElementById('font-size-select'),
        inputSessionTitle: document.getElementById('session-title'),
        indicatorTime: document.getElementById('indicator-time'),
        indicatorWords: document.getElementById('indicator-words'),
        indicatorWpm: document.getElementById('indicator-wpm'),
        flowPulse: document.getElementById('flow-pulse'),
        overlayDanger: document.getElementById('overlay-danger'),
        hardcoreCountdown: document.getElementById('hardcore-countdown'),
        countdownSec: document.getElementById('countdown-sec'),
        btnCompleteSession: document.getElementById('btn-complete-session'),
        btnAbandonSession: document.getElementById('btn-abandon-session'),
        btnEditorSoundToggle: document.getElementById('btn-editor-sound-toggle'),
        btnEditorAmbientToggle: document.getElementById('btn-editor-ambient-toggle'),

        // Results
        resHeaderBox: document.getElementById('results-header-box'),
        resTitle: document.getElementById('results-title'),
        resMotivation: document.getElementById('results-motivation'),
        resStatWords: document.getElementById('res-stat-words'),
        resStatWpm: document.getElementById('res-stat-wpm'),
        resStatTime: document.getElementById('res-stat-time'),
        resStatGoal: document.getElementById('res-stat-goal'),
        velocitySvg: document.getElementById('velocity-svg'),
        btnCopyResult: document.getElementById('btn-copy-result'),
        btnExport: document.getElementById('btn-export'),
        exportMenu: document.getElementById('export-menu'),
        btnExportMd: document.getElementById('export-md'),
        btnExportTxt: document.getElementById('export-txt'),
        btnHome: document.getElementById('btn-home'),
        resultsPreviewText: document.getElementById('results-preview-text'),

        // Settings / Modals
        btnCloseSettings: document.getElementById('btn-close-settings'),
        chkDarkMode: document.getElementById('chk-dark-mode'),
        rangeVolTypewriter: document.getElementById('volume-typewriter'),
        rangeVolAmbient: document.getElementById('volume-ambient'),
        valVolTypewriter: document.getElementById('val-vol-typewriter'),
        valVolAmbient: document.getElementById('val-vol-ambient'),
        selectTypewriterProfile: document.getElementById('typewriter-profile'),
        chkTypewriterBell: document.getElementById('chk-typewriter-bell'),
        chkAutoSave: document.getElementById('chk-auto-save'),
        btnSaveSettings: document.getElementById('btn-save-settings'),
        
        // Daily Goal
        chkShowDailyGoal: document.getElementById('chk-show-daily-goal'),
        inputDailyGoal: document.getElementById('input-daily-goal'),
        dailyGoalWidget: document.getElementById('daily-goal-widget'),
        dailyGoalText: document.getElementById('daily-goal-text'),
        btnHideDailyGoal: document.getElementById('btn-hide-daily-goal'),
        btnShowDailyGoalTab: document.getElementById('btn-show-daily-goal-tab'),

        // Compile Modal Controls
        compileFormatSelect: document.getElementById('compile-format-select'),
        compileAuthorInput: document.getElementById('compile-author-input'),
        compileIncludeFolderNames: document.getElementById('compile-include-folder-names'),
        compileIncludeDocTitles: document.getElementById('compile-include-doc-titles'),
        compilePageBreaksFolders: document.getElementById('compile-page-breaks-folders'),
        compileSeparatorSelect: document.getElementById('compile-separator-select'),
        compileTreeList: document.getElementById('compile-tree-list'),
        btnCompileSelectAll: document.getElementById('btn-compile-select-all'),
        btnCompileDeselectAll: document.getElementById('btn-compile-deselect-all'),
        btnTriggerCompile: document.getElementById('btn-trigger-compile'),
        btnCancelCompile: document.getElementById('btn-cancel-compile'),
        btnCloseCompile: document.getElementById('btn-close-compile'),
        compilePdfSettingsSection: document.getElementById('compile-pdf-settings-section'),
        compileTemplateSelect: document.getElementById('compile-template-select'),
        compileTrimSizeSelect: document.getElementById('compile-trim-select'),
        compileDropCaps: document.getElementById('compile-drop-caps'),
        compileRunningHeaders: document.getElementById('compile-headers-select'),
        compileTitleOrnament: document.getElementById('compile-ornament-select'),
        compileLivePreviewBox: document.getElementById('compile-live-preview-box'),
        compilePreviewTrimLabel: document.getElementById('preview-trim-label'),
        compilePreviewHeader: document.querySelector('#compile-live-preview-box .preview-header'),
        compilePreviewHeaderAuthor: document.getElementById('preview-header-author'),
        compilePreviewHeaderTitle: document.getElementById('preview-header-title'),
        compilePreviewOrnament: document.querySelector('#compile-live-preview-box .preview-ornament'),
        compilePreviewDropCap: document.querySelector('#compile-live-preview-box .preview-drop-cap'),
        compilePreviewFirstWordRest: document.querySelector('#compile-live-preview-box .preview-first-word-rest'),
        compilePreviewFirstWordNormal: document.querySelector('#compile-live-preview-box .preview-first-word-normal')
    };
};
